### PR TITLE
Add Animated Welcome Text

### PR DESCRIPTION
**Pull request by kinnam888**
1. Add new animated print text function
2. Remove static welcome message

### CODE REVIEW

**Review by rmondal-official — CHANGES_REQUESTED** [review]
**Would you please do a little change ?**

I want you to change the animation from one whole text to multiple text. 

The first text to appear, then change and then the next text to appear animatedly. These will display all 4 texts one by one and then it will repeat from first.

And please add a cursor also.

**Comment by kinnam888** [comment]
Can you provide more explanation on the cursor part? or any example?

**Comment by rmondal-official** [comment]
Oo Sure !
It's just like the normal cursor you see in text editor while typing. Did you get it or want an example video ?

**Review by rmondal-official — APPROVED** [review]
Hello @kinnam888  ,

I wanted to take a moment to express my heartfelt gratitude for the enhancement you've contributed to our project through this pull request. Your commitment to improving the project with your valuable input has not gone unnoticed.

The enhancement you added has significantly improved the functionality and has been a pivotal step forward for us. It's contributions like yours that drive open source projects towards excellence and innovation.

Thank you once again for your important contribution. We are looking forward to more of your innovative ideas and collaboration in the future.

Best regards,
**Rajesh Mondal**

**Pull request merged**
